const constants = {

    // Actions

    SORT_COLORS: "SORT_COLORS",
    ADD_COLOR: "ADD_COLOR",
    RATE_COLOR: "RATE_COLOR",
    REMOVE_COLOR: "REMOVE_COLOR",
    LOAD_COLORS: "LOAD_COLORS",
    COLORS_RECEIVED: "COLORS_RECEIVED",

    // States

    SORTED_BY_DATE: "SORTED_BY_DATE",
    SORTED_BY_TITLE: "SORTED_BY_TITLE",
    SORTED_BY_RATING: "SORTED_BY_RATING"

}

export default constants